root = "."
testdata_dir = "testdata"

[build]
cmd = "go build -o basic_gemini"
bin = ""
full_bin = ""
include_dir = ["/workspaces/genkit/go/genkit"]
include_ext = ["go", "tpl", "tmpl", "html"]
include_file = ["go.mod", "go.sum"]

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true